---
title: "Plot Münch et al. (2017) figures"
author: "Thomas Münch"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plot Münch et al. (2017) figures}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  rmarkdown.html_vignette.check_title = FALSE,
  comment = "#>"
)
```

```{r setup}
library(TrenchR)
```

## Overview

This vignette reproduces the figures shown in the publication Münch, T.,
Kipfstuhl, S., Freitag, J., Meyer, H. and Laepple, T.: Constraints on
post-depositional isotope modifications in East Antarctic firn from analysing
temporal changes of isotope profiles, _The Cryosphere_, **11**, 2175–2188,
doi: [10.5194/tc-11-2175-2017](https://doi.org/10.5194/tc-11-2175-2017), 2017.

## Figure 1

```{r, fig.height = 6.75, fig.width = 16}
TrenchR:::produceTC17Figures("f1")
```

## Figure 2

```{r, fig.height = 8, fig.width = 8}
TrenchR:::produceTC17Figures("f2")
```

## Figure 3

```{r, fig.height = 6, fig.width = 9.75}
TrenchR:::produceTC17Figures("f3a")
```

```{r, fig.height = 6, fig.width = 9.75}
TrenchR:::produceTC17Figures("f3b")
```

```{r, fig.height = 6, fig.width = 8}
TrenchR:::produceTC17Figures("f3c")
```

## Figure 4

```{r, fig.height = 6, fig.width = 8}
TrenchR:::produceTC17Figures("f4")
```

## Figure 5

```{r, fig.height = 6, fig.width = 8}
TrenchR:::produceTC17Figures("f5")
```

## Figure 6

```{r, fig.height = 6, fig.width = 16}
TrenchR:::produceTC17Figures("f6")
```

## Figure 7

```{r, fig.height = 6, fig.width = 12}
TrenchR:::produceTC17Figures("f7")
```
